### ISSUE TITLE
return s and s.strip()，改成 return s.strip()就无法得到正确的结果

### ISSUE THREAD

**Issue by ybbswc** [michaelliao/learn-python3#20]
`return s and s.strip()`
这个应该如何理解呢？and在这里的作用是什么呢？为何不能是
`return s.strip()`

搜索到了原因：
https://stackoverflow.com/questions/45799757/why-does-return-s-and-s-strip-work-when-using-filter

**Comment by kuacuia** [comment]
同问。。。

**Comment by zainbeau** [comment]
and 返回一个True 或者False.你说呢
