### ISSUE TITLE
Queue is not defined

### ISSUE THREAD

**Issue by lovelock** [michaelliao/learn-python3#21]
queue is imported while Queue is used, when you try get result from queue for 11 times the error will be threw.

**Comment by cclauss** [comment]
[flake8](http://flake8.pycqa.org) testing of https://github.com/michaelliao/learn-python3 on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./samples/commonlib/use_urllib.py:53:17: F821 undefined name 'urllib'
proxy_handler = urllib.request.ProxyHandler({'http': 'http://www.example.com:3128/'})
                ^
./samples/commonlib/use_urllib.py:54:22: F821 undefined name 'urllib'
proxy_auth_handler = urllib.request.ProxyBasicAuthHandler()
                     ^
./samples/commonlib/use_urllib.py:56:10: F821 undefined name 'urllib'
opener = urllib.request.build_opener(proxy_handler, proxy_auth_handler)
         ^
./samples/multitask/task_worker.py:33:12: F821 undefined name 'Queue'
    except Queue.Empty:
           ^
4     F821 undefined name 'urllib'
4
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by cclauss** [comment]
Bump on this one.
