### ISSUE TITLE
您好，运行learning.py有什么用呢？做什么用的？一直没理解

### ISSUE THREAD

**Issue by anyexch** [michaelliao/learn-python3#33]
运行learning.py有什么用呢？做什么用的？一直没理解，烦请解释一下，初学者。。。

**Comment by MagicYang1989** [comment]
运行后挂在后台，在浏览器上就能直接实现代码，不用你在python里实现

发自我的vivo智能手机

anyexch <notifications@github.com>编写：

**Comment by sos450724492** [comment]
其实就是方便一些哈哈哈

**Comment by wutaosang** [comment]
可以直接在浏览器中运行代码，但是缩进有点麻烦

**Comment by hezhen20** [comment]
我的理解就是，通过在电脑上运行learning.py文件，能够使你在网页上就能运行写的代码
