### ISSUE TITLE
中文字符转换还是有问题

### ISSUE THREAD

**Issue by pariswu1988** [michaelliao/learn-python3#6]
按照老师讲的方法，第一步，将notepad++的格式转变为UTF-8 without BOM
第二步，在代码前面加上# -_\- coding: utf-8 -_-
在做《字符串和编码》的练习时，中文输出还是二进制
是否我的计算机默认语言设置有问题？
代码如下：
# -_\- coding: utf-8 -_-

s1=72
s2=85
r=(s2-s1)/s1*100
print ('the percentage: %.1f%%' % r)

在cmd界面调用后：
C:\work>python percent.py
Traceback (most recent call last):
  File "percent.py", line 5, in <module>
    print ('\u767e\u5206\u6bd4\u4e3a: %.1f%%' % r)#show xx.x%, %%means showing one %
  File "C:\Users\paris\AppData\Local\Programs\Python\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

**Comment by Graphic9** [comment]
it's '# -*- coding: utf-8 -*-' not the '# -- coding: utf-8 --'
