### ISSUE TITLE
如何其它方式登廖雪峰峰官方网站【登陆方式】

### ISSUE THREAD

**Issue by jianghai861** [michaelliao/learn-python3#84]
在登陆 廖雪峰官方网站 https://www.liaoxuefeng.com/auth/signin 时只能使用微博登陆，这比较尴尬。不经常玩微博，也不想注册微博账号，希望可以其它方式登陆，如QQ号码登陆，微信登陆，或者本网站注册账号登陆可否？

**Comment by vijaychandhu2000** [comment]
Buuu

**Comment by vijaychandhu2000** [comment]
Gyv568u

**Comment by ranbowhy** [comment]
learning...

**Comment by ChangeWold** [comment]
biu biu biu

**Comment by verneyleaf** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
