### ISSUE TITLE
learn-python3/samples/functional/prime_numbers.py 这个电脑跑不出来吧？

### ISSUE THREAD

**Issue by dhdsjy** [michaelliao/learn-python3#9]
关于用生成器找素数的这个问题， 代码逻辑很清楚 但是电脑怎么跑不出来？求解答

**Comment by nmkiby** [comment]
代码没问题，我用的python 3.5.3

**Comment by dhdsjy** [comment]
我用的是2.7 不知道为什么 一跑就死机。。

在 2017-04-13 12:49:32，"王维鹏" <notifications@github.com> 写道：


代码没问题，我用的python 3.5.3

**Comment by michaelliao** [comment]
只能在py3跑
