### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Oskarnuttree** [michaelliao/learn-python3#96]

**Comment by verneyleaf** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by har8shith** [comment]
please assign me this issue:)

**Comment by Hakim-CS** [comment]
I didn't understand

**Comment by verneyleaf** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
